<?php

namespace AppBundle\Repository;

/**
 * IndirizzoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndirizzoRepository extends \Doctrine\ORM\EntityRepository
{
}
